export const FORBIDDEN = "/forbidden"
export const LOGIN = "/auth/login"
export const REGISTER = "/auth/register"
export const VERIFIED_ACCOUNT = "/auth/verify-account"
export const SUCCESSFUL_VERIFIED_ACCOUNT = "/auth/success-verify-account"
export const FORGOT_PASSWORD = "/auth/forgot-password"
export const PROJECTS = "/app/projects"
export const DASHBOARD = "/app/dashboard"